aliases:
    cat: bat
    catp: bat -P
    cz: chezmoi
    czg: chezmoi git
    db: distrobox
    fleeks: cd ~/.local/share/fleek
    g: git
    nah: git reset --hard; git clean -df;
    tf: terraform
bling: none
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: false
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - _1password
    - asdf-vm
    - btop
    - cascadia-code
    - cheat
    - chezmoi
    - diff-so-fancy
    - fd
    - fzf
    - git
    - github-cli
    - htop
    - jq
    - kubectl
    - mc
    - neofetch
    - neovim
    - nixfmt
    - nodejs-18_x
    - pre-commit
    - python3
    - ranger
    - ripgrep
    - tldr
    - xclip
    - yq
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/.config/emacs/bin
programs:
    - atuin
    - bat
    - direnv
    - emacs
    - exa
    - navi
    - starship
    - zoxide
shell: bash
systems:
    - arch: x86_64
      hostname: limiting-factor
      os: linux
      username: tbjers
unfree: true
users:
    - email: torgny@bjers.org
      name: Torgny Bjers
      ssh_private_key_file: ""
      ssh_public_key_file: ""
      username: tbjers
