aliases:
    cz: chezmoi
    czg: chezmoi git
    db: distrobox
    fleeks: cd ~/.local/share/fleek
    g: git
    nah: git reset --hard; git clean -df;
    tf: terraform
bling: high
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: false
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - cascadia-code
    - chezmoi
    - fd
    - helix
    - mc
    - nixfmt
    - nodejs-18_x
    - pre-commit
    - python3
    - ranger
    - shellcheck
    - shfmt
    - asdf-vm
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/.config/emacs/bin
programs:
    - emacs
    - gpg
    - navi
shell: bash
systems:
    - arch: x86_64
      hostname: limiting-factor
      os: linux
      username: tbjers
unfree: true
users:
    - email: torgny@bjers.org
      name: Torgny Bjers
      ssh_private_key_file: ""
      ssh_public_key_file: ""
      username: tbjers
